---
# tasks file for Grafana_confiduration
- name: Add repository key for Grafana
  apt_key:
    url: https://packages.grafana.com/gpg.key
    validate_certs: no

- name: Add repository for Grafana
  copy:
    content: "deb https://packages.grafana.com/oss/deb stable main"
    dest: /etc/apt/sources.list.d/grafana.list

- name: Update 
  apt: 
    update_cache: yes

- name: Install requared instruments
  apt:
    state: latest
    name: grafana

- name: Install/update Grafana zabbix plugin
  community.grafana.grafana_plugin:
    name: alexanderzobnin-zabbix-app
    version: latest
    state: present

- name: Start & enable grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: yes
